'comp: @angular-ru/cdk':
  - libs/cdk/**/*

'comp: @angular-ru/dev-dependencies':
  - libs/dev-dependencies/**/*

'comp: @angular-ru/commitlint':
  - libs/commitlint/**/*

'comp: @angular-ru/typescript':
  - libs/typescript/**/*

'comp: @angular-ru/eslint-plugin-enterprise':
  - libs/eslint-plugin-enterprise/**/*

'comp: @angular-ru/eslint-config-enterprise':
  - libs/eslint-config-enterprise/**/*

'comp: @angular-ru/jest':
  - libs/jest/**/*

'comp: @angular-ru/prettier':
  - libs/prettier/**/*

'comp: @angular-ru/renovate':
  - libs/renovate/**/*
