"comp: @angular-ru/build-tools":
    - packages/build-tools/*
    - packages/build-tools/**/*

"comp: @angular-ru/commitlint-config":
    - packages/commitlint-config/*
    - packages/commitlint-config/**/*

"comp: @angular-ru/common":
    - packages/common/*
    - packages/common/**/*

"comp: @angular-ru/eslint-config":
    - packages/eslint-config/*
    - packages/eslint-config/**/*

"comp: @angular-ru/eslint-plugin":
    - packages/eslint-plugin/*
    - packages/eslint-plugin/**/*

"comp: @angular-ru/flex-layout":
    - packages/flex-layout/*
    - packages/flex-layout/**/*

"comp: @angular-ru/http":
    - packages/http/*
    - packages/http/**/*

"comp: @angular-ru/jest-utils":
    - packages/jest-utils/*
    - packages/jest-utils/**/*

"comp: @angular-ru/logger":
    - packages/logger/*
    - packages/logger/**/*

"comp: @angular-ru/ng-excel-builder":
    - packages/ng-excel-builder/*
    - packages/ng-excel-builder/**/*

"comp: @angular-ru/ng-table-builder":
    - packages/ng-table-builder/*
    - packages/ng-table-builder/**/*

"comp: @angular-ru/prettier-config":
    - packages/prettier-config/*
    - packages/prettier-config/**/*

"comp: @angular-ru/renovate-config":
    - packages/renovate-config/*
    - packages/renovate-config/**/*

"comp: @angular-ru/stream":
    - packages/stream/*
    - packages/stream/**/*

"comp: @angular-ru/tooltip":
    - packages/tooltip/*
    - packages/tooltip/**/*

"comp: @angular-ru/tsconfig":
    - packages/tsconfig/*
    - packages/tsconfig/**/*
