name: Angular-RU SDK action auto push
description: Auto push fixable code

inputs:
  commit-message:
    description: Commit message
    required: false
    default: 'chore: fix formatting'

runs:
  using: composite
  steps:
    - name: Auto push
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      shell: bash
      run: |
        git config --global user.name "angular-ru-bot"
        git config --global user.email "angular-ru@yandex.ru"
        git config remote.origin.url https://x-access-token:${{ secrets.ANGULAR_RU_BOT_PAT }}@github.com/$GITHUB_REPOSITORY

        echo "git status"
        git status
        echo "------"

        echo "git add ."
        git add .
        echo "------"

        echo "git commit ..."
        git commit -m "${{ inputs.commit-message }}" \
                   --no-verify --no-edit \
                   --author="${{ inputs.username }} <${{ inputs.email }}>" && \
        git push --force-with-lease || true
