name: Angular-RU SDK action auto push
description: Auto push fixable code

inputs:
  commit-message:
    description: Commit message
    required: false
    default: 'chore: fix formatting'
  username:
    description: Git username
    required: true
  token:
    description: Token
    required: true
  email:
    description: Git user email
    required: true

runs:
  using: composite
  steps:
    - name: Auto push
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      shell: bash
      run: |
        git config --global user.name "${{ inputs.username }}"
        git config --global user.email "${{ inputs.email }}"
        git config remote.origin.url https://x-access-token:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY

        echo "git status"
        git status
        echo "------"

        echo "git add ."
        git add .
        echo "------"

        echo "git commit ..."
        git commit -m "${{ inputs.commit-message }}" \
             --no-verify --no-edit \
             --author="${{ inputs.username }} <${{ inputs.email }}>" && \
        git push --force-with-lease || true
