language: node_js
node_js:
    - 'node' # latest

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn clean
    - yarn pretty:lint
    - yarn package:sort --check
    - yarn build:prepare
    - yarn build:lib
    - yarn lint
    - yarn test
    - yarn build:app


before_deploy:
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/Angular-RU/angular-ru-sdk.git" > /dev/null 2>&1
    - git checkout master
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
    provider: script
    script: 'yarn lerna publish && yarn deploy'
    skip_cleanup: true
    on:
        branch: master
        condition: '$TRAVIS_PULL_REQUEST =~ ^(true|false)$'
