language: node_js
node_js:
  - 'node' # latest

cache:
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  - yarn test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash publish.sh
