export { capitalize } from './capitalize';
export { filter, FilterPredicate, FilterPredicateFn } from './filter';
export { generateQuickGuid } from './generate-quick-guid';
export { getByteSize } from './get-byte-size';
export { getCountSpacesOnString } from './get-count-spaces-on-string';
export { getFirstSymbol } from './get-first-symbol';
export { getLastSymbol } from './get-last-symbol';
export { isString } from './is-string';
export { removeLastSymbol } from './remove-last-symbol';
export { removeNonNumericSymbols } from './remove-non-numeric-symbols';
export { replaceEveryCommaOnDot } from './replace-every-comma-on-dot';
export { splitOnUniqueValues } from './split-on-unique-values';
export { stringify } from './stringify';
export { toStringValue } from './to-string-value';
export { trim } from './trim';
