// eslint-disable-next-line
export enum TableFilterType {
    START_WITH = 'START_WITH',
    END_WITH = 'END_WITH',
    CONTAINS = 'CONTAINS',
    DOES_NOT_CONTAIN = 'DOES_NOT_CONTAIN',
    EQUALS = 'EQUALS',
    DOES_NOT_EQUAL = 'DOES_NOT_EQUAL',
    MORE_THAN = 'MORE_THAN',
    MORE_OR_EQUAL = 'MORE_OR_EQUAL',
    LESS_THAN = 'LESS_THAN',
    LESS_OR_EQUAL = 'LESS_OR_EQUAL',
    IS_FILLED = 'IS_FILLED',
    CONTAINS_ONE_OF_VALUES = 'CONTAINS_ONE_OF_VALUES',
    INTERVAL = 'INTERVAL'
}
