export const META_PATH_VARIABLE: 'META_PATH_VARIABLE' = 'META_PATH_VARIABLE';
export const META_REQUEST_BODY: 'META_REQUEST_BODY' = 'META_REQUEST_BODY';
export const META_REQUEST_PARAM: 'META_REQUEST_PARAM' = 'META_REQUEST_PARAM';
export const KEY_REQUEST_BODY: 'KEY_REQUEST_BODY' = 'KEY_REQUEST_BODY';
