export const META_PATH_VARIABLE: 'META_PATH_VARIABLE' = 'META_PATH_VARIABLE' as const;
export const META_REQUEST_BODY: 'META_REQUEST_BODY' = 'META_REQUEST_BODY' as const;
export const META_REQUEST_PARAM: 'META_REQUEST_PARAM' = 'META_REQUEST_PARAM' as const;
export const KEY_REQUEST_BODY: 'KEY_REQUEST_BODY' = 'KEY_REQUEST_BODY' as const;
