export { checkValueIsEmpty } from './check-value-is-empty';
export { detectChanges } from './detect-changes';
export { getBodyRect } from './get-body-rect';
export { copyBuffer } from './copy-buffer';
export { isNotNil } from './is-not-nil';
export { isNil } from './is-nil';
export { $cast } from './$cast';
export { $any } from './$any';
export { isIE } from './is-ie';
