export const enum DefaultDateIntervalSuggestion {
    TODAY = 'TODAY',
    YESTERDAY = 'YESTERDAY',
    CALENDAR_WEEK = 'CALENDAR_WEEK',
    LAST_3_DAYS = 'LAST_3_DAYS',
    LAST_7_DAYS = 'LAST_7_DAYS',
    LAST_99_DAYS = 'LAST_99_DAYS',
    FIRST_DAY_OF_INTERVAL = 'FIRST_DAY_OF_INTERVAL',
    LAST_99_DAYS_OF_INTERVAL = 'LAST_99_DAYS_OF_INTERVAL'
}
