name: Auto Assign to Project(s)

on:
    issues:
        types: [labeled]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PROJECTS_BASE_URL: 'https://github.com/Angular-RU/angular-ru-sdk/projects'

jobs:
    assign-one-project:
        runs-on: ubuntu-latest
        name: Assign to one project
        env:
            PROJECT_ID: 1
            LABEL_FOR_ASSIGN: 'documentation'
        steps:
            - name: Assign issues to documentation project
              uses: srggrs/assign-one-project-github-action@1.3.0
              if: contains(github.event.issue.labels.*.name, '${{ env.LABEL_FOR_ASSIGN }}')
              with:
                  project: '${{ env.PROJECTS_BASE_URL }}/${{ env.PROJECT_ID }}'
