name: Auto rebase with default branche

on:
    push:
        branches: [master]
jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare git
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git config --global push.default simple
                  git config --global user.name "angular-ru"
                  git config --global user.email "angular-ru@yandex.ru"
                  git config remote.origin.url https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY

            - uses: peter-evans/rebase@v1
              with:
                  base: master
