name: CI
on:
  push:
    branches: [master]

jobs:
  autorebase:
    runs-on: ubuntu-20.04
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: '30s'

      - uses: peter-evans/rebase@v1.3.0
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}
          base: master

concurrency:
  group: autorebase-${{ github.head_ref }}
  cancel-in-progress: true
