name: CI
on:
  push:
    branches: [master]

jobs:
  autorebase:
    runs-on: ubuntu-20.04
    steps:
      - uses: peter-evans/rebase@v1.3.0
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}
          base: master
