name: CI Autorebase
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  autorebase:
    runs-on: ubuntu-22.04
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: '30s'

      - uses: peter-evans/rebase@v2.0.1
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}
          base: master

concurrency:
  group: autorebase-${{ github.head_ref }}
  cancel-in-progress: true
