name: Rebase all pull requests on push to the base branch

on: [push]

jobs:
    rebase:
        runs-on: ubuntu-latest
        env:
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - uses: peter-evans/rebase@v1
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  base: master
