name: Rebase all pull requests on push to the base branch

on:
  push:
    branches: [master]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v1
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}
          base: master
