name: Check automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.ANGULAR_RU_BOT_PAT }}
          MERGE_REMOVE_LABELS: automerge
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_RETRY_SLEEP: 10000
          MERGE_LABELS: automerge
          UPDATE_METHOD: rebase
          MERGE_METHOD: rebase
          BASE_BRANCHES: main
          MERGE_FORKS: false
          MERGE_RETRIES: 3

      - name: feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
