name: ci/autoupdate
on: [push]

jobs:
    autoupdate:
        name: autoupdate
        runs-on: ubuntu-18.04
        steps:
            - uses: docker://chinthakagodawita/autoupdate-action:v1
              env:
                  GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'
                  DRY_RUN: 'true'
                  MERGE_MSG: 'chore: branch was auto-updated'
                  EXCLUDED_LABELS: 'renovate'
                  MERGE_CONFLICT_ACTION: 'ignore'
