name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build packages
        run: yarn build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
