name: CI Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v3

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: | # todo fix later
          npx nx build cdk
          npx nx build ngxs
          npx nx build jest

      - name: Run build packages
        run:
          npx nx run-many --target=build --parallel=1 --all --exclude $(npx nx affected:apps --base=origin/master
          --plain)

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
