name: CI Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run build packages
        run: npx nx run-many --target=build --parallel=1

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
