name: Angular-RU SDK pipelines
on: [push]

env:
    CI_MODE: 'true'
    NODE_VERSION: '16.9.x'
    BASE_BRANCH: 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel an already running workflow
              uses: fkirc/skip-duplicate-actions@v3.4.1
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  cancel_others: true

            - uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  persist-credentials: false
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Prepare git
              run: |
                  git config --global push.default simple
                  git config --global user.name "angular-ru"
                  git config --global user.email "angular-ru@yandex.ru"
                  git config remote.origin.url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY

            - name: Restore cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}--${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Verify major angular version
              if: ${{ github.ref != 'refs/heads/${{ env.BASE_BRANCH }}' }}
              run: yarn verify:ng

            - name: Build packages
              run: yarn build

            - name: Linting code
              if: ${{ github.ref != 'refs/heads/${{ env.BASE_BRANCH }}' }}
              run: yarn commitlint --from=HEAD~1 && yarn run-p format lint

            - name: Run unit tests
              if: ${{ github.ref != 'refs/heads/${{ env.BASE_BRANCH }}' }}
              run: yarn test

            - name: Build integration apps
              if: ${{ github.ref != 'refs/heads/${{ env.BASE_BRANCH }}' }}
              run: yarn integration

            - name: Deploy npm packages (only for ${{ env.BASE_BRANCH }})
              if: ${{ github.ref == 'refs/heads/${{ env.BASE_BRANCH }}' }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
                  GH_TOKEN=${{ secrets.GH_TOKEN }} yarn lerna publish

            # Auto push fixable code
            - name: Get last commit message
              if: ${{ github.ref != 'refs/heads/${{ env.BASE_BRANCH }}' }}
              id: last-commit-message
              run: |
                  echo "::set-output name=msg::$(git log -1 --pretty=%s)"
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: ${{ steps.last-commit-message.outputs.msg }}
                  commit_options: '--amend --no-edit'
                  push_options: '--force'
                  skip_fetch: true
