name: CI Integrations
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  integrations:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v2

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build integrations apps
        run: npx nx run-many --target=build --parallel=1 --all --exclude $(nx affected:libs --base=master --plain)

concurrency:
  group: integration-${{ github.head_ref }}
  cancel-in-progress: true
