name: Labeling new issue
on:
    issues:
        types: ['opened']
jobs:
    auto-label:
        runs-on: ubuntu-latest
        steps:
            - uses: Renato66/auto-label@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  ignore-comments: true
                  labels-synonyms:
                      '{"documentation": ["docs", "documentation"], "bug":["error","need fix","not working",
                      "fix"],"feature":["feat", "feature"],"question":["help"]}'
                  labels-not-allowed: '["good first issue"]'
                  default-labels: '["triage"]'
