name: Automatically label new pull requests based on the paths of files being changed

on: [push]

jobs:
    triage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@main
              with:
                  repo-token: ${{ secrets.GH_TOKEN }}
