name: CI
on: [pull_request]

jobs:
  labeler:
    # it just blocks the action from running in PRs in peoples forks
    if: ${{ github.repository_owner == 'Angular-RU' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yml
          sync-labels: true

concurrency:
  group: labeler-${{ github.head_ref }}
  cancel-in-progress: true
