name: CI Label approved PR
on: [pull_request]

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: '1'
          ADD_LABEL: 'ready to merge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
