name: ci/labels
on: [push]

jobs:
    triage:
        name: triage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@main
              with:
                  repo-token: '${{ secrets.GH_TOKEN }}'
