name: CI Label about changes
on: [pull_request]

jobs:
  label-found-changes:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yml
          sync-labels: true

concurrency:
  group: labeler-${{ github.head_ref }}
  cancel-in-progress: true
