name: CI Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v4

      - name: Setup Git
        id: git-setup
        uses: ./.github/actions/git
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run format
        run: npm run prettier -- --write

      - name: Run lint
        run: npm run lint

      - name: Autocommit fixed files and push
        uses: ./.github/actions/autopush
        with:
          username: ${{ steps.git-setup.outputs.username }}
          email: ${{ steps.git-setup.outputs.email }}
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
