name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}

      - name: Check commit name
        run: yarn commitlint --from=HEAD~1

      - name: Format by prettier
        run: yarn format

      - name: Linting code by ESLint
        run: |
          # build eslint common dependencies before
          yarn lerna run --scope @angular-ru/cdk build:lib
          yarn lerna run --scope @angular-ru/ngxs build:lib
          yarn lerna run --scope @angular-ru/eslint-plugin-enterprise build:lib

          # run lint
          yarn lint

      - uses: ./.github/actions/autopush
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
