name: CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v2.4.0

      - name: Setup Git
        id: git-setup
        uses: ./.github/actions/git
        with:
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run commitlint
        run: |
          yarn commitlint \
                --from ${{ github.event.pull_request.base.sha }} \
                --to ${{ github.event.pull_request.head.sha }} \
                --verbose

      - name: Run prettier
        run: yarn format

      - name: Run build artifacts dependent
        run: |
          yarn lerna run --scope @angular-ru/cdk build:lib
          yarn lerna run --scope @angular-ru/ngxs build:lib
          yarn lerna run --scope @angular-ru/eslint-plugin-enterprise build:lib

      - name: Run eslint
        run: yarn lint

      - name: Autocommit fixed files and push
        uses: ./.github/actions/autopush
        with:
          username: ${{ steps.git-setup.outputs.username }}
          email: ${{ steps.git-setup.outputs.email }}

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
