name: ci/build
on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}--yarn--${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Temporarily save node_modules
              uses: actions/upload-artifact@v2
              with:
                  name: node_modules
                  path: node_modules

    lint:
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Checkstyle
              run: |
                  yarn commitlint --from=HEAD~1
                  yarn format
                  yarn lint
