name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.9.1
        with:
          configurationFile: libs/renovate/renovate.js
          token: ${{ secrets.ANGULAR_RU_BOT_PAT }}
        env:
          LOG_LEVEL: 'debug'

concurrency:
  group: renovate-${{ github.head_ref }}
  cancel-in-progress: true
