name: CI Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Scan repo for find local actions
        uses: actions/checkout@v2

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run build artifacts dependent
        run: yarn nx build jest

      - name: Run unit tests
        run: yarn nx run-many --target=test --all --collect-coverage

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/cdk/
          flags: summary,cdk
          name: cdk

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/ngxs/
          flags: summary,ngxs
          name: ngxs

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/jest/
          flags: summary,jest
          name: jest

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/eslint-config-enterprise/
          flags: summary,eslint-config-enterprise
          name: eslint-config-enterprise

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
