# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular-RU SDK CI

on: [push]

jobs:
    build:
        name: Building
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

    deployment:
        name: Deployments
        runs-on: ubuntu-latest
        needs: [build]
        if: contains('refs/heads/master', github.ref)
        steps:
            - uses: actions/checkout@v2
            - name: Deploy
            - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
            - run: yarn deploy
