# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular-RU SDK CI

on: [push]

jobs:
    build-and-deploy:
        if: "!contains(github.event.head_commit.message , 'ci skip')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  persist-credentials: false

            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restore lerna
              uses: actions/cache@v2
              with:
                  path: |
                      .cache
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}--build-cache-hash--${{ hashFiles('**/yarn.lock') }}

            - name: Run install step
              run: |
                  yarn --ignore-engines --frozen-lockfile

            - name: Run building libraries step
              run: |
                  yarn build:lib

            - name: Run lint step
              run: |
                  yarn format
                  yarn lint --fix

            - name: Run test step
              run: yarn test --parallel

            - name: Run building integration apps step
              run: yarn build:app --parallel

            - name: Deploy integration apps
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              if: contains('refs/heads/master', github.ref)
              run: yarn deploy --parallel

            - name: Deploy npm packages
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              if: contains('refs/heads/master', github.ref)
              run: |
                  git config --global push.default simple
                  git config --global user.name "angular-ru"
                  git config --global user.email "angular-ru@yandex.ru"
                  git config remote.origin.url https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
                  GH_TOKEN=${{ secrets.GH_TOKEN }} yarn lerna publish

            # auto git commit
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "ci: apply changes"
