# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular-RU SDK CI

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Run install step
              run: |
                  yarn install
                  yarn clean
                  yarn build:prepare

            - name: Run building libraries step
              run: |
                  yarn build:lib

            - name: Run lint step
              run: |
                  yarn pretty:lint
                  yarn package:sort --check
                  yarn lint

            - name: Run test step
              run: yarn test

            - name: Run building integration apps step
              run: yarn build:app

            - name: Deploy step
              with:
                  GITHUB_TOKEN: ${{ secrets.GH_DEPLOY }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_DEPLOY }}
              if: contains('refs/heads/master', github.ref)
              run: yarn deploy
